### ISSUE TITLE
'unsupported protocol scheme "git"' in latest Kfctl (v1.0-rc.2-13-g521fcfe)

### ISSUE THREAD

**Issue by pavanaiyar** [kubeflow/kfctl#217]
Background
---
In the latest kfctl version `v1.0-rc.2-13-g521fcfe` the following go-getter format repository URL:

```
  repos:
  - name: manifests
    uri:  git::https://github.org.com/ORG/kubeflow-manifests.git
  version: v1.0-rc.0
```

A `kfctl build -V -f kfctl-local.yaml` Results in: 

```
failed to build kfApp from URI kfctl-local.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: could not sync cache. Error:  (kubeflow.error): Code 400 with message: couldn't download URI git::https://github.ORG.com/ORG/kubeflow-manifests.git Error Get "git::https://github.ORG.com/ORG/kubeflow-manifests.git": unsupported protocol scheme "git"
```

Whereas with kfctl version `v0.7.1` this happily fetches and generates the same configurations

Could someone please advise if this is intended and if there are alternate methods to describe a 'private'/enterprise GitHub repo of manifests?
