### ISSUE TITLE
Add an option to the AWS plugin not to add fsx inline policy which is too permissive

### ISSUE THREAD

**Issue by descampsk** [kubeflow/kfctl#232]
When you use the AWS Plugin, kfctl will automaticaly add the [iam_csi_fsx_policy.json] policy to the worker nodes, even if we don't use the FSX CSI.

This policy is too permissive:

```
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "*"
    }, 
```

We need to delete manually this inline policy to be able to use Kubeflow in production for security reasons.

I would like to have an option (useFsx: false for example) to the AWS Plugin here: 
```
  - kind: KfAwsPlugin
    metadata:
      name: aws
    spec:
      useFsx: false
      auth:
        cognito:
          certArn: arn:aws:acm:us-west-2:xxxxx:certificate/xxxxxxxxxxxxx-xxxx
          cognitoAppClientId: xxxxxbxxxxxx
          cognitoUserPoolArn: arn:aws:cognito-idp:us-west-2:xxxxx:userpool/us-west-2_xxxxxx
          cognitoUserPoolDomain: your-user-pool
      region: us-west-2
      roles:
      - eksctl-kubeflow-aws-nodegroup-ng-a2-NodeInstanceRole-xxxxx
```

to allow kfctl to install or not the inline fsx policy.

In addition, it will be perfect if it's possible for all inlines policy.
