### ISSUE TITLE
creating secrets from kfDef during installation

### ISSUE THREAD

**Issue by SatwikBhandiwad** [kubeflow/kfctl#308]
```
secrets:
  - name: env_password
    secretSource:
      envSource:
        name: ENV_PASSWORD_NAME
  - name: plain_text_password
    secretSource:
      literalSource:
        value: 12345
```

Added the above part in kfDef and expected it to create two secrets in kubeflow namespace during installation. Is this how it works? 
I posted the same question on slack and did not get any response, so posting it here.
