### ISSUE TITLE
kfctl not using correct url

### ISSUE THREAD

**Issue by croesuslab** [kubeflow/kfctl#360]
I am trying to setup Kubeflow on my K3S server listening on port 6443. For some reason, the setup tries to install on port 8080, which is not used. Is there a way to change this url? 

I downloaded the kfctl_k8s_istio.v1.0.2.yaml config file. When I run the kfctl apply command, I get the following error:
```
failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 400 with message: couldn't create namespace kubeflow Error: Post "http://localhost:8080/api/v1/namespaces": dial tcp 127.0.0.1:8080: connect: connection refused
```

Cluster infos:
```
>kubectl config current-context
default

>kubectl config get-contexts
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
*         default   default   default

>kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: ***
    username: admin

>kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4+k3s1", GitCommit:"97b7a0e9df2883f08028fb7171c1e62fc1899a0c", GitTreeState:"clean", BuildDate:"2020-06-18T01:30:45Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

>kfctl version
kfctl v1.0.2-0-ga476281
```
