### ISSUE TITLE
Add support for Managed AWS Kubeflow Deployment 

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/kfctl#398]
Specifically, we will add logic in `KfctlAwsPlugin` to read Native AWS resources information (Optional for users until they want to use managed AWS KF deployment).

What we want: 

```
Managed: 
  - RDS: 
       - endPoint: XXXXXXX
       - DBUsername: XXXX
       - DBPassword: XXXXX
   - S3: 
      - bucket-name: XXXXXX
   - awsAuth:
      - accessKey: XXXXXX
      - secretKey: XXXXXX
```

Combined with [manifest changes](https://github.com/kubeflow/manifests/issues/1495) for adding support.
