### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[istio-token]

### ISSUE THREAD

**Issue by zhangchunsheng** [kubeflow/kfctl#406]
kubeflow / cache-deployer-deployment log

```
Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[kubeflow-pipelines-cache-deployer-sa-token-s9jjq istio-envoy sds-uds-path istio-token]: timed out waiting for the condition

MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
```

**Comment by zhangchunsheng** [comment]
add flag in /etc/kubernetes/manifests/kube-apiserver.yaml
- --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
- --service-account-issuer=kubernetes.default.svc

**Comment by jbottum** [comment]
@zhangchunsheng which cloud are you running on ? AWS, GCP, on-prem ?

**Comment by zhangchunsheng** [comment]
> @zhangchunsheng which cloud are you running on ? AWS, GCP, on-prem ?

Aliyun

**Comment by shantanuVerma7** [comment]
Add following flags/feature gates in you API Server. In the file /etc/kubernetes/manifests/kube-apiserver.yaml

```
- --feature-gates=TokenRequest=true
- --feature-gates=TokenRequestProjection=true
```
It should look something like this
```
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.28.60
    - --allow-privileged=true
    - --feature-gates=TokenRequest=true
    - --feature-gates=TokenRequestProjection=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt

```
