### ISSUE TITLE
Issue with Issuer URL for Dex - Google Connector Integration

### ISSUE THREAD

**Issue by muthurajr** [kubeflow/kfctl#433]
I have installed Kubeflow 1.1.0 with Istio & Dex, and exposed it on a public domain (mlapps.example.com). When connecting Dex with any SAML connectors, it provides an option to override issuer URL for AuthnRequest purpose (entityIssuer). https://dexidp.io/docs/connectors/saml/

When Google connector (https://dexidp.io/docs/connectors/google/) is used, is there any approach to override just for the validation purpose without changing the base issuer URL?

```Error: time="2020-11-09T18:26:19Z" level=error msg="Connector \"google\" returned error when creating callback: expected callback URL \"http://dex.auth.svc.cluster.local:5556/dex/callback\" did not match the URL in the config \"https://mlapps.example.com/dex/callback\""```

Dex Configuration:
```
issuer: http://dex.auth.svc.cluster.local:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
enablePasswordDB: true
staticPasswords:
- email: admin@kubeflow.com
  hash: *******
  username: admin
  userID: ********
staticClients:
- id: kubeflow-oidc-authservice
  redirectURIs: ["/login/oidc"]
  name: 'Dex Login Application'
  secret: **********
connectors:
- type: google
  id: google
  name: Google
  config:
    clientID: $GOOGLE_CLIENT_ID
    clientSecret: $GOOGLE_CLIENT_SECRET
    redirectURI: https://mlapps.example.com/dex/callback
    serviceAccountFilePath: /etc/dex/gauth/googleAuth.json
    adminEmail: admin@**********
    hostedDomains:
     - **************
    groups:
     - ************
```

**Comment by tyg03485** [comment]
Is there any solution for this issue?

**Comment by muthurajr** [comment]
@tyg03485 I don't see config.issuer in https://dexidp.io/docs/connectors/google/. Is this undocumented functionality?

**Comment by tyg03485** [comment]
it means
```
issuer: { MyEndpointOfDex }
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
...
connectors:
- type: google
  id: google
  name: Google
  config:
    clientID: $GOOGLE_CLIENT_ID
    clientSecret: $GOOGLE_CLIENT_SECRET
    redirectURI: https://mlapps.example.com/dex/callback
    serviceAccountFilePath: /etc/dex/gauth/googleAuth.json
    adminEmail: admin@**********
    hostedDomains:
     - **************
    groups:
     - ************
```
ref. https://dexidp.io/docs/oidc-certification-setup/
