### ISSUE TITLE
kfctl apply from pricate kfdef on private and enterprize github

### ISSUE THREAD

**Issue by moficodes** [kubeflow/kfctl#468]
right now the only way we can deploy kubeflow with kfctl is if the manifest is coming from a public repository and the kfdef is either downloaded or is also a public url.

it would be useful if we added a way to download private github files using token and from enterprise github.

**Comment by arun-vc** [comment]
This would be very useful since some component overlays need to be private

**Comment by soleares** [comment]
If you're trying to add a private github repo to your kfdef in order to specify custom versions of some applications this works now in master:

- Build kfdef from master. It needs this PR: https://github.com/kubeflow/kfctl/pull/247
	- Clone repo
	- `make build`
	- `cd bin`
	- `cp kfctl /usr/local/bin/`
- Append an entry to the repos list. This assumes that you use SSH to access your private github repos.
```
  repos:
  - name: manifests
    uri: git::https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  - name: my-manifests
    uri: git::git@github.com:myorg/myrepo.git
```
- If you need to access a specific branch/tag/commit you can add a ref
```
  repos:
  - name: manifests
    uri: git::https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  - name: my-manifests
    uri: git::git@github.com:myorg/myrepo.git?ref=mybranch
```
