### ISSUE TITLE
junit files in presubmits not copied to the right bucket

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kfctl#58]
Our E2E tests for presubmits aren't copying the junit files to the write GCS location; which is why results aren't showing up in testgrid and spyglass.

Here's the command executed by copy-artifacts.

```
gsutil -m rsync -r /mnt/test-data-volume/kubeflow-presubmit-kfctl-go-iap-istio-4313-b6589cf-4149-fe75/output gs://kubeflow-ci_temp/pr-lo
gs/pull/kubeflow_kubeflow/4313/kubeflow-presubmit/None
```

This is the wrong subdirectory; it should not be None.

The correct directory for this PR should be 

```
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/4313/kubeflow-presubmit/1184279996345094149/artifacts/
```

Related to kubeflow/testing#257

**Comment by jlewi** [comment]
Bump to P0 looks like its an issue for periodic jobs as well.

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-periodic-master/1184534691647066120

```
gsutil -m rsync -r /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/output gs://kubeflow-ci_temp/logs/kubeflow
-periodic-master/None
```

Looking at the workflow here's the invocation of the copy_artifacts step

```
     command:
      - python
      - -m
      - kubeflow.testing.prow_artifacts
      - --artifacts_dir=/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/output
      - copy_artifacts
      - --bucket=kubeflow-ci_temp
      - --suffix=fakesuffix
```

**Comment by jlewi** [comment]
Here's the code
https://github.com/kubeflow/testing/blob/f7a75caa7b1ccf79d516479facc22e7abb852433/py/kubeflow/testing/prow_artifacts.py#L143

Here's where its getting the value
https://github.com/kubeflow/testing/blob/f7a75caa7b1ccf79d516479facc22e7abb852433/py/kubeflow/testing/prow_artifacts.py#L121

So the final bit should be the build number

Here are the environment variables for the step.

```
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/gcp-credentials/key.json
      - name: PYTHONPATH
        value: /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/src/kubeflow/kubeflow:/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/src/kubeflow/kubeflow/py:/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/src/kubeflow/testing/py:/mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/src/kubeflow/tf-operator/py
      - name: GOPATH
        value: /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4
      - name: KUBECONFIG
        value: /mnt/test-data-volume/kubeflow-periodic-master-kfctl-go-iap-endpoint-6120-6fd4/kfctl_test/.kube/kubeconfig
      - name: BUILD_ID
        value: '1184534691647066120'
      - name: JOB_SPEC
        value: '{"type":"periodic","job":"kubeflow-periodic-master","buildid":"1184534691647066120","prowjobid":"9ebe3f5c-f041-11e9-90f3-324215531d4f"}'
      - name: REPO_OWNER
        value: kubeflow
      - name: PROW_JOB_ID
        value: 9ebe3f5c-f041-11e9-90f3-324215531d4f
      - name: JOB_TYPE
        value: periodic
      - name: JOB_NAME
        value: kubeflow-periodic-master
      - name: REPO_NAME
        value: kubeflow
```

It looks like we are setting BUILD_ID; not BUILD_NUMBER.

The docs say BUILD_ID
https://github.com/kubernetes/test-infra/blob/45246b09ed105698aa8fb928b7736d14480def29/prow/jobs.md#job-environment-variables

Based on the logs printed out by run_e2e_workflow.sh

```
INFO|2019-10-16T18:21:13|/src/kubeflow/testing/py/kubeflow/testing/util.py|45| Running: ks-13 param set --env=kubeflow-periodic-master-deployapp-6120-9e10 click_deploy_test prow_env BUILD_ID=1184534691647066120,BUILD_NUMBER=1184534691647066120,JOB_NAME=kubeflow-periodic-master,JOB_TYPE=periodic,REPO_NAME=kubeflow,REPO_OWNER=kubeflow 
```
It looks like both BUILD_ID and BUILD_NUMBER is set.
